// Pure-function tests for lib/handles-manifest.mjs -- no fs, no git fixture. See
// test/handles-ownership-cli.test.mjs for the end-to-end version of this same decision tree.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { classifyFile, extractResolverOwnerFeatureId, BSKEL_GENERATED_MARKER } from '../lib/handles-manifest.mjs';

test('classifyFile: file does not exist -> create, regardless of any other input', () => {
	assert.equal(classifyFile({ exists: false, diskHash: null, manifestEntryHash: 'anything', freshRenderHash: 'x', matchesPristineRender: true }), 'create');
	assert.equal(classifyFile({ exists: false, diskHash: null, manifestEntryHash: null, freshRenderHash: 'x', matchesPristineRender: false }), 'create');
});

test('classifyFile: manifest entry matches disk (untouched since generation) and fresh render matches too -> unchanged', () => {
	const action = classifyFile({ exists: true, diskHash: 'h1', manifestEntryHash: 'h1', freshRenderHash: 'h1', matchesPristineRender: false });
	assert.equal(action, 'unchanged');
});

test('classifyFile: manifest entry matches disk (untouched) but a fresh render now differs -> update (propagates template/live-value drift, D-security-7)', () => {
	const action = classifyFile({ exists: true, diskHash: 'h1', manifestEntryHash: 'h1', freshRenderHash: 'h2-new-authority', matchesPristineRender: false });
	assert.equal(action, 'update');
});

test('classifyFile: manifest entry exists but disk hash has moved -> conflict (a human touched it)', () => {
	const action = classifyFile({ exists: true, diskHash: 'h-edited-by-human', manifestEntryHash: 'h-original', freshRenderHash: 'h-fresh', matchesPristineRender: false });
	assert.equal(action, 'conflict');
});

test('classifyFile: no manifest entry, disk content matches a pristine render, and matches the fresh render too -> adopt-unchanged', () => {
	const action = classifyFile({ exists: true, diskHash: 'h1', manifestEntryHash: null, freshRenderHash: 'h1', matchesPristineRender: true });
	assert.equal(action, 'adopt-unchanged');
});

test('classifyFile: no manifest entry, disk content matches a pristine render but NOT the fresh render (e.g. a different feature id) -> adopt-update', () => {
	const action = classifyFile({ exists: true, diskHash: 'h-owned-by-feature-001', manifestEntryHash: null, freshRenderHash: 'h-for-feature-002', matchesPristineRender: true });
	assert.equal(action, 'adopt-update');
});

test('classifyFile: no manifest entry and disk content matches NO pristine render -> conflict (fail-closed, cannot tell stale-template from human edit)', () => {
	const action = classifyFile({ exists: true, diskHash: 'h-mystery', manifestEntryHash: null, freshRenderHash: 'h-fresh', matchesPristineRender: false });
	assert.equal(action, 'conflict');
});

test('extractResolverOwnerFeatureId: recovers the feature id from a real resolver javadoc marker', () => {
	const content = `/**\n * Generated by backend-skeleton ({@code bskel handles emit}) for feature 001-widget-management.\n */\npublic class WidgetResolver {}\n`;
	assert.equal(extractResolverOwnerFeatureId(content), '001-widget-management');
});

test('extractResolverOwnerFeatureId: no marker present -> null (fails closed to CONFLICT upstream, not a guess)', () => {
	assert.equal(extractResolverOwnerFeatureId('public class WidgetResolver { /* hand-written, no marker at all */ }'), null);
	assert.equal(extractResolverOwnerFeatureId(''), null);
	assert.equal(extractResolverOwnerFeatureId(null), null);
});

test('extractResolverOwnerFeatureId: a bogus/malformed marker (no trailing period) does not match -> null, not a wrong capture', () => {
	const content = 'Generated by backend-skeleton ({@code bskel handles emit}) for feature 001-widget-management without a period anywhere';
	assert.equal(extractResolverOwnerFeatureId(content), null);
});

test('BSKEL_GENERATED_MARKER is the exact shared prefix present in both the infra and resolver templates', () => {
	assert.match('Generated by backend-skeleton ({@code bskel handles emit}). Do not hand-edit -- change the source template', new RegExp(BSKEL_GENERATED_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
	assert.match('Generated by backend-skeleton ({@code bskel handles emit}) for feature 001-widget-management.', new RegExp(BSKEL_GENERATED_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
});
