#!/usr/bin/env bash
# Generated by backend-skeleton (stack choice: postgres-dev-db). Self-contained in this repo --
# does not require backend-skeleton to be installed to run. See scripts/_bskel-lib.sh for
# shared helpers (the same env_upsert() the ngrok stack choice's script already uses).
#
# D-docker-postgres-stack: this is a LOCAL DEV database only, not a production deployment
# recipe -- no TLS, a fixed default password, a single unreplicated container. Named here as a
# deliberate, permanent scope limit, the same "narrow and honest beats broad and wrong" posture
# A12's own scoping already established for this backlog.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
source scripts/_bskel-lib.sh

COMPOSE_FILE="docker-compose.postgres.yml"
ENV_FILE=".env"
POSTGRES_USER="${POSTGRES_USER:-app}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-app}"
POSTGRES_DB="${POSTGRES_DB:-app}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
TIMEOUT_S=30

while [ $# -gt 0 ]; do
	case "$1" in
		--timeout) TIMEOUT_S="$2"; shift 2 ;;
		*) echo "unknown argument: $1" >&2; exit 14 ;;
	esac
done

if ! command -v docker >/dev/null 2>&1; then
	echo "docker not found on PATH -- install Docker before running this script" >&2
	exit 1
fi

export POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB POSTGRES_PORT
echo "starting postgres via $COMPOSE_FILE..."
docker compose -f "$COMPOSE_FILE" up -d

echo "waiting for postgres to accept connections (up to ${TIMEOUT_S}s)..."
waited=0
until docker compose -f "$COMPOSE_FILE" exec -T db pg_isready -U "$POSTGRES_USER" >/dev/null 2>&1; do
	waited=$((waited + 1))
	if [ "$waited" -ge "$TIMEOUT_S" ]; then
		echo "postgres did not become ready within ${TIMEOUT_S}s -- check: docker compose -f $COMPOSE_FILE logs" >&2
		exit 1
	fi
	sleep 1
done

DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}"
env_upsert "$ENV_FILE" DATABASE_URL "$DATABASE_URL"
echo "postgres is up, wrote DATABASE_URL to $ENV_FILE"
echo "note: if your app reads a differently-named variable, copy/rename this value (and pass that name to \`bskel scan --db --database-url-env <NAME>\` for schema introspection) -- see .env.example"
