#!/usr/bin/env bash
# Generated by backend-skeleton (stack choice: ngrok). Self-contained in this repo -- does not
# require backend-skeleton to be installed to run. See scripts/_bskel-lib.sh for shared helpers.
#
# D-ngrok: ephemeral vs. reserved-domain mode is switched by whether NGROK_DOMAIN is set --
# not a fixed choice made at codegen time. D8 (DECISIONS.md): this script writes .env; the
# agent that ran `bskel stack apply` never touches .env directly -- only a human-invoked
# runtime script does, per CLAUDE.md's ".env is never read/edited by the agent" rule.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
source scripts/_bskel-lib.sh

PORT="${PORT:-8080}"
ENV_FILE=".env"
EXEC_CMD=""
PRINT_ONLY=0
TIMEOUT_S=30

while [ $# -gt 0 ]; do
	case "$1" in
		--port) PORT="$2"; shift 2 ;;
		--exec) EXEC_CMD="$2"; shift 2 ;;
		--print-only) PRINT_ONLY=1; shift ;;
		--timeout) TIMEOUT_S="$2"; shift 2 ;;
		*) echo "unknown argument: $1" >&2; exit 14 ;;
	esac
done

: "${NGROK_AUTHTOKEN:?NGROK_AUTHTOKEN not set -- see .env.example, get one at https://dashboard.ngrok.com/get-started/your-authtoken}"

NGROK_ARGS=(http "$PORT" --log=stdout)
if [ -n "${NGROK_DOMAIN:-}" ]; then
	echo "using reserved domain: $NGROK_DOMAIN"
	NGROK_ARGS+=(--domain "$NGROK_DOMAIN")
else
	echo "no NGROK_DOMAIN set -- using an ephemeral URL (different every run)"
fi

# D-security-5: mktemp, not a predictable /tmp/bskel-ngrok-$$.log name -- the PID-based name
# let another local process race a symlink into that exact path before ngrok's stdout/stderr
# ever gets written to it. Found by the Codex security review.
LOG_FILE=$(mktemp "${TMPDIR:-/tmp}/bskel-ngrok-XXXXXX.log")
ngrok "${NGROK_ARGS[@]}" > "$LOG_FILE" 2>&1 &
NGROK_PID=$!
mkdir -p .sbf 2>/dev/null || true
echo "$NGROK_PID" > .sbf/ngrok.pid 2>/dev/null || true

cleanup() {
	kill "$NGROK_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

echo "waiting for ngrok tunnel (up to ${TIMEOUT_S}s)..."
TUNNEL_JSON=$(wait_for_tunnel "http://127.0.0.1:4040/api/tunnels" "$TIMEOUT_S") || {
	echo "ngrok did not come up within ${TIMEOUT_S}s -- log:" >&2
	cat "$LOG_FILE" >&2
	exit 1
}
PUBLIC_URL=$(extract_https_url "$TUNNEL_JSON")
if [ -z "$PUBLIC_URL" ]; then
	echo "could not extract an https tunnel URL from ngrok's API response: $TUNNEL_JSON" >&2
	exit 1
fi
echo "tunnel up: $PUBLIC_URL"

if [ "$PRINT_ONLY" -eq 1 ]; then
	echo "$PUBLIC_URL"
	exit 0
fi

# Spring reads .env only at boot (spring.config.import) -- writing these AFTER the app has
# already started does nothing until the next restart. That's why this script's default mode
# is "write env, then tell you to (re)start", and --exec exists for a one-shot tunnel-then-run.
env_upsert "$ENV_FILE" PUBLIC_BASE_URL "$PUBLIC_URL"
env_append_unique "$ENV_FILE" AUTH_LOGIN_ALLOWED_ORIGINS "$PUBLIC_URL"
echo "wrote PUBLIC_BASE_URL and appended to AUTH_LOGIN_ALLOWED_ORIGINS in $ENV_FILE"

if [ -n "$EXEC_CMD" ]; then
	echo "starting: $EXEC_CMD"
	exec $EXEC_CMD
fi

echo "tunnel is running (pid $NGROK_PID) -- (re)start your app now to pick up the env vars just written."
wait "$NGROK_PID"
