import { ADAPTERS, LOAD_ERRORS } from './registry.mjs';

// A1 §7 (unchanged): the exact default string previously inlined below -- kept as a module
// constant so an adapter can override it via `result.apiSurfaceSource` without this file needing
// to know which adapters exist. Neither shipped adapter overrides it today, so output is
// byte-identical to before G1.
const DEFAULT_API_SURFACE_SOURCE = 'source-annotations only (this scan does not check for a committed ' +
	'OpenAPI document -- if one is generated by the build, pass it via --openapi-file to ' +
	'`contract emit`)';

// D3 (see DECISIONS.md): verdict drives a disposition state machine, not an agent question.
// A module scores >= COLLISION_THRESHOLD only when it's a strong, multi-signal match (module
// name + controller/table/path/operationId overlap) -- e.g. scanning Team-IZ-Backend for
// "organization" scores the `organization` module's module-name match (10) alone at the
// threshold, before even counting its controller/table/path hits.
const COLLISION_THRESHOLD = 10;

function normalize(s) {
	return (s || '').toLowerCase();
}

function matches(text, terms) {
	const t = normalize(text);
	if (!t) return false;
	return terms.some((term) => {
		const nt = normalize(term);
		return nt && (t.includes(nt) || nt.includes(t));
	});
}

function scoreModule(mod, terms) {
	let score = 0;
	if (matches(mod.module, terms)) score += 10;
	for (const c of mod.controllers) {
		if (matches(c.className, terms)) score += 6;
		if (matches(c.basePath, terms)) score += 5;
		for (const ep of c.endpoints) {
			if (matches(ep.path, terms)) score += 5;
			if (matches(ep.operationId, terms)) score += 5;
		}
	}
	for (const e of mod.entities) {
		if (matches(e.table, terms)) score += 8;
		if (matches(e.className, terms)) score += 6;
	}
	for (const en of mod.enums) {
		if (matches(en.name, terms)) score += 3;
	}
	return score;
}

// G1: adapter dispatch, replacing the previous hardcoded two-branch if/else. `adapters` is
// injectable (defaults to the real zero-registration registry) purely as a test seam for
// arbitration/ambiguity tests -- every real caller gets the default. See D-adapter-registry in
// DECISIONS.md.
export function runScan({ repoRoot, terms, includeDb = false, adapters = ADAPTERS }) {
	const detections = adapters
		.map((a) => ({ a, d: a.detect(repoRoot) }))
		.filter(({ d }) => d != null)
		// Not relying on the caller to have pre-sorted `adapters` -- specificity is the sole
		// source of truth for arbitration, computed here regardless of input order.
		.sort((x, y) => y.a.specificity - x.a.specificity || x.a.id.localeCompare(y.a.id));

	if (detections.length === 0) {
		throw new Error(
			`no scanner adapter detected this repo -- tried: ${adapters.map((a) => a.id).join(', ') || '(no adapters loaded)'}` +
			`${LOAD_ERRORS.length > 0 ? `; ${LOAD_ERRORS.length} adapter(s) failed to load, see \`bskel doctor\`` : ''}`,
		);
	}
	const topSpecificity = detections[0].a.specificity;
	const tiedAtTop = detections.filter(({ a }) => a.specificity === topSpecificity);
	if (tiedAtTop.length > 1) {
		// O6-style refusal: when it's genuinely ambiguous, name every candidate and stop, rather
		// than silently picking one (same principle as handles/emit.mjs's detectBasePackage()).
		throw new Error(
			`ambiguous adapter selection -- ${tiedAtTop.map(({ a }) => a.id).join(', ')} all detected this repo at ` +
			`specificity ${topSpecificity}. Give one a higher specificity, or make its detect() more precise.`,
		);
	}

	const { a: chosen, d: detection } = detections[0];
	const result = chosen.scan(repoRoot, detection);
	const adapter = chosen.id;
	const confidence = chosen.confidence;
	const modules = result.modules;
	const pathPrefixSignals = result.pathPrefixSignals ?? [];
	const apiSurfaceSource = result.apiSurfaceSource ?? DEFAULT_API_SURFACE_SOURCE;

	// O6: score alone isn't a deterministic sort key -- two modules tying on score fall back to
	// whatever order they were already in, which traces back to non-deterministic rg discovery
	// order in the adapters above (mitigated there too, but a second determinism layer here is
	// cheap and doesn't depend on every adapter getting it right). Module name is a stable,
	// meaningful secondary key.
	const scored = modules
		.map((m) => ({ ...m, score: scoreModule(m, terms) }))
		.sort((a, b) => b.score - a.score || a.module.localeCompare(b.module));

	const relatedModules = scored.filter((m) => m.score > 0);
	const collisions = relatedModules.filter((m) => m.score >= COLLISION_THRESHOLD);

	let verdict = 'greenfield';
	if (collisions.length > 0) verdict = 'collision';
	else if (relatedModules.length > 0) verdict = 'adjacent';

	const unknowns = [];
	if (!includeDb) {
		unknowns.push('DB not scanned (Plane C is opt-in via --db, off by default and not yet implemented -- see A4 in CATALOG.md)');
	}
	// A1 §7: this scan can't correct a global path prefix (only --openapi-file's real-document
	// reconciliation can, see D-openapi-reconciliation) -- but it CAN tell a user who doesn't know
	// that flag exists that the defect is likely present, before they ever emit a wrong contract.
	if (pathPrefixSignals.length > 0) {
		const detail = pathPrefixSignals
			.map((s) => `${s.kind} in ${s.file}${s.prefix ? ` (prefix "${s.prefix}")` : s.pattern ? ` (pattern "${s.pattern}")` : ''}`)
			.join('; ');
		unknowns.push(
			`this repo applies a global path prefix outside controller source (${detail}) -- contract ` +
			'paths built from source annotations alone (no --openapi-file) will be missing it. Generate ' +
			'a real OpenAPI document and pass it to `bskel contract emit --openapi-file <path>`. See ' +
			'D-openapi-reconciliation in DECISIONS.md.',
		);
	}

	return {
		schema: 'sbf.scan-report/1',
		terms,
		adapter,
		confidence,
		api_surface_source: apiSurfaceSource,
		verdict,
		path_prefix_signals: pathPrefixSignals,
		related_modules: relatedModules,
		collisions,
		unknowns,
	};
}
