import { ADAPTERS, LOAD_ERRORS } from './registry.mjs';

// D-scanner-evidence (CATALOG.md's D3 -- NOT the same as this file's own "D3" comment below,
// which is this repo's internal DECISIONS.md numbering for something unrelated; see the
// A2/A3 precedent in CATALOG.md for this exact collision class): weight per evidence signal -- the exact 8 values scoreModule() always
// used, now named and shared between evidence collection and score summation instead of being
// scattered `score += N` literals.
const SIGNAL_WEIGHTS = Object.freeze({
	module_name: 10,
	controller_class: 6,
	controller_path: 5,
	endpoint_path: 5,
	endpoint_operation_id: 5,
	entity_table: 8,
	entity_class: 6,
	enum_name: 3,
});

// D-scanner-evidence: caps how many matches of the SAME signal type contribute to a module's score -- without
// this, a controller with many endpoints inflates score linearly regardless of real relevance
// (generic-grep.mjs already fixed exactly this class of bug once, for className-per-route; this
// closes the same gap for endpoint_path/endpoint_operation_id, which were still uncapped). Every
// match still appears in the evidence array (`counted:false` beyond the cap) -- capping affects
// scoring, not transparency. Value chosen empirically, not guessed: validated against
// Team-IZ-Backend (organization/curriculum modules) to confirm every previously-correct verdict
// still holds at this value -- see D-scanner-evidence in DECISIONS.md for the sweep.
const CAP_PER_SIGNAL = 5;

// D-scanner-evidence: splits on non-alphanumeric runs AND camelCase boundaries (lower->upper, and an uppercase
// run's last letter -> Uppercase+lowercase, so "APIController" -> "API","Controller" not
// "APIController" whole) -- the SAME function handles both identifiers (className, no separators,
// relies on camelCase splitting) and paths (basePath/endpoint path, no camelCase, relies on
// separator splitting) correctly, since each just exercises the half of the regex it needs.
const CAMEL_BOUNDARY_RE = /([a-z0-9])([A-Z])|([A-Z]+)([A-Z][a-z])/g;

export function tokenize(s) {
	if (!s) return [];
	const spaced = String(s).replace(CAMEL_BOUNDARY_RE, (_, a, b, c, d) => (a ? `${a} ${b}` : `${c} ${d}`));
	return spaced.split(/[^a-zA-Z0-9]+/).filter(Boolean).map((t) => t.toLowerCase());
}

// A1 §7 (unchanged): the exact default string previously inlined below -- kept as a module
// constant so an adapter can override it via `result.apiSurfaceSource` without this file needing
// to know which adapters exist. Neither shipped adapter overrides it today, so output is
// byte-identical to before G1.
const DEFAULT_API_SURFACE_SOURCE = 'source-annotations only (this scan does not check for a committed ' +
	'OpenAPI document -- if one is generated by the build, pass it via --openapi-file to ' +
	'`contract emit`)';

// D3 (see DECISIONS.md): verdict drives a disposition state machine, not an agent question.
// A module scores >= COLLISION_THRESHOLD only when it's a strong, multi-signal match (module
// name + controller/table/path/operationId overlap) -- e.g. scanning Team-IZ-Backend for
// "organization" scores the `organization` module's module-name match (10) alone at the
// threshold, before even counting its controller/table/path hits.
const COLLISION_THRESHOLD = 10;

// D-scanner-evidence: `termTokens` matches `textTokens` if it appears as a CONTIGUOUS
// subsequence, comparing token-by-token with a bidirectional prefix check (not exact equality --
// "organization" must still match the token "organizations", a real plural-form case the old
// substring matcher supported by accident). This replaces the old whole-string, un-tokenized
// `t.includes(nt) || nt.includes(t)` -- the catalog's "symmetric substring matching" complaint --
// which let a short piece of text match anywhere inside an unrelated long term, or a short term
// match anywhere inside an unrelated identifier, crossing real word boundaries either way (e.g.
// term "man" matching inside the token "management" is still possible here since it's a real
// prefix of that ONE token, but term "man" can no longer match by spanning from the tail of one
// word into the head of the next, the way whole-string substring search allowed).
function tokensMatch(termTokens, textTokens) {
	if (termTokens.length === 0 || termTokens.length > textTokens.length) return false;
	for (let start = 0; start <= textTokens.length - termTokens.length; start++) {
		let allMatch = true;
		for (let i = 0; i < termTokens.length; i++) {
			const tt = termTokens[i];
			const xt = textTokens[start + i];
			if (!(xt.startsWith(tt) || tt.startsWith(xt))) { allMatch = false; break; }
		}
		if (allMatch) return true;
	}
	return false;
}

// Returns every term (not just whether ANY matched) that matches `text` -- D-scanner-evidence
// needs one evidence record per matching term, not just a boolean.
function matchingTerms(text, terms) {
	const textTokens = tokenize(text);
	if (textTokens.length === 0) return [];
	return terms.filter((term) => tokensMatch(tokenize(term), textTokens));
}

// D-scanner-evidence: caps PER SIGNAL TYPE at collection time, not by collecting everything and
// filtering afterward -- found live, not anticipated: collecting every raw match first (a
// controller with 600 endpoints all matching one term produces 1200 evidence records for that
// ONE module) pushed a real scan report past Node's default 1MB `execFileSync` buffer, crashing
// the exact >64KB-report regression test this codebase already had (see D-process-exit-audit's
// pipe-truncation history in DECISIONS.md -- this is the same failure class, a different cause).
// Capping during collection keeps report size bounded regardless of repo size, and every
// recorded entry always counts toward score (no separate `counted` flag needed) -- signals that
// hit the cap are named in `cappedSignals` (one string per module, not one flag per entry) so
// `bskel scan explain` can still say "N further widget-path matches exist, not shown" without an
// unbounded per-entry record for each of them.
class EvidenceCollector {
	constructor() {
		this.evidence = [];
		this.counts = new Map();
		this.cappedSignals = new Set();
	}

	// Encounter order is already deterministic here without a separate sort step: callers walk
	// controllers/entities/enums in the adapter's own already-sorted (O6: rg --files sorted) file
	// order, endpoints in document order within one file, and terms in the user's own --terms
	// order -- the same ordering scoreModule() always scored in.
	add(signal, term, value, file, line) {
		const count = (this.counts.get(signal) ?? 0) + 1;
		this.counts.set(signal, count);
		if (count > CAP_PER_SIGNAL) {
			this.cappedSignals.add(signal);
			return;
		}
		this.evidence.push({ signal, term, value, weight: SIGNAL_WEIGHTS[signal], file, line: line ?? null });
	}
}

// D-scanner-evidence: walks every signal-bearing field exactly once, in the same order
// scoreModule() always scored them in.
function collectEvidence(mod, terms) {
	const c = new EvidenceCollector();
	for (const term of matchingTerms(mod.module, terms)) c.add('module_name', term, mod.module, null, null);
	for (const controller of mod.controllers) {
		for (const term of matchingTerms(controller.className, terms)) c.add('controller_class', term, controller.className, controller.file, controller.line);
		for (const term of matchingTerms(controller.basePath, terms)) c.add('controller_path', term, controller.basePath, controller.file, controller.line);
		for (const ep of controller.endpoints) {
			for (const term of matchingTerms(ep.path, terms)) c.add('endpoint_path', term, ep.path, controller.file, ep.line);
			for (const term of matchingTerms(ep.operationId, terms)) c.add('endpoint_operation_id', term, ep.operationId, controller.file, ep.line);
		}
	}
	for (const e of mod.entities) {
		for (const term of matchingTerms(e.table, terms)) c.add('entity_table', term, e.table, e.file, e.line);
		for (const term of matchingTerms(e.className, terms)) c.add('entity_class', term, e.className, e.file, e.line);
	}
	for (const en of mod.enums) {
		for (const term of matchingTerms(en.name, terms)) c.add('enum_name', term, en.name, en.file, en.line);
	}
	return c;
}

export function scoreModule(mod, terms) {
	const c = collectEvidence(mod, terms);
	const score = c.evidence.reduce((sum, e) => sum + e.weight, 0);
	return { score, evidence: c.evidence, cappedSignals: [...c.cappedSignals].sort() };
}

// A4 (D-db-schema-plane): case-insensitive comparison against every already-scanned entity's own
// `.table` field -- tables the live DB has but no source entity declares, and entities whose
// declared table isn't found live, both become plain-string `unknowns` entries (same shape every
// other unknown in this report already uses), never a blocking verdict change. This is the
// concrete "reveal live drift" value CATALOG.md's A4 Why names.
export function computeDbDrift(liveTables, relatedModules) {
	const liveNames = new Set(liveTables.map((t) => t.name.toLowerCase()));
	const declaredTables = new Map(); // lowercased table name -> {module, entity}
	for (const m of relatedModules) {
		for (const e of m.entities ?? []) {
			if (e.table) declaredTables.set(e.table.toLowerCase(), { module: m.module, entity: e.className });
		}
	}

	const findings = [];
	for (const name of liveNames) {
		if (!declaredTables.has(name)) findings.push(`live DB table "${name}" has no matching source entity in any scanned module (Plane C drift)`);
	}
	for (const [table, { module, entity }] of declaredTables) {
		if (!liveNames.has(table)) findings.push(`entity ${entity} (module "${module}") declares table "${table}", but it was not found in the live DB (Plane C drift)`);
	}
	return findings;
}

// G1: adapter dispatch, replacing the previous hardcoded two-branch if/else. `adapters` is
// injectable (defaults to the real zero-registration registry) purely as a test seam for
// arbitration/ambiguity tests -- every real caller gets the default. See D-adapter-registry in
// DECISIONS.md.
//
// A4: `dbSchema` (`{migrations, live}` or null) is computed by the CALLER, not fetched here --
// env var resolution and the live DB connection itself are CLI-boundary concerns (matching how
// every other env-var-driven input in this codebase is resolved at the bin/bskel.mjs layer, never
// inside a "pure" lib/scanner function), and keeps this function synchronous (Plane C's real I/O
// is `await`ed by the caller before ever calling this).
//
// D-zero-config-scan: `rgAvailable` is the SAME kind of CLI-boundary-resolved input as `dbSchema`
// -- bin/bskel.mjs computes it once via lib/doctor.mjs's binaryAvailable('rg') and hands it in as
// plain data. Defaults to `true` so every existing call site (this whole test suite included)
// stays byte-for-byte unchanged.
export function runScan({ repoRoot, terms, includeDb = false, dbSchema = null, adapters = ADAPTERS, rgAvailable = true }) {
	const detections = adapters
		.map((a) => ({ a, d: a.detect(repoRoot) }))
		.filter(({ d }) => d != null)
		// Not relying on the caller to have pre-sorted `adapters` -- specificity is the sole
		// source of truth for arbitration, computed here regardless of input order.
		.sort((x, y) => y.a.specificity - x.a.specificity || x.a.id.localeCompare(y.a.id));

	if (detections.length === 0) {
		throw new Error(
			`no scanner adapter detected this repo -- tried: ${adapters.map((a) => a.id).join(', ') || '(no adapters loaded)'}` +
			`${LOAD_ERRORS.length > 0 ? `; ${LOAD_ERRORS.length} adapter(s) failed to load, see \`bskel doctor\`` : ''}`,
		);
	}
	const topSpecificity = detections[0].a.specificity;
	const tiedAtTop = detections.filter(({ a }) => a.specificity === topSpecificity);
	if (tiedAtTop.length > 1) {
		// O6-style refusal: when it's genuinely ambiguous, name every candidate and stop, rather
		// than silently picking one (same principle as handles/emit.mjs's detectBasePackage()).
		throw new Error(
			`ambiguous adapter selection -- ${tiedAtTop.map(({ a }) => a.id).join(', ')} all detected this repo at ` +
			`specificity ${topSpecificity}. Give one a higher specificity, or make its detect() more precise.`,
		);
	}

	const { a: chosen, d: detection } = detections[0];
	const result = chosen.scan(repoRoot, detection);
	const adapter = chosen.id;
	const confidence = chosen.confidence;
	const modules = result.modules;
	const pathPrefixSignals = result.pathPrefixSignals ?? [];
	const apiSurfaceSource = result.apiSurfaceSource ?? DEFAULT_API_SURFACE_SOURCE;
	// S2 (D-gate-precision, continued): the adapter's own real read-set, persisted so
	// lib/gate-definitions.mjs's `scan` gate can hash it for a precise staleness token instead of
	// a repo-wide head_sha proxy. Optional (`?? []`) so an adapter that doesn't populate it (a
	// third-party adapter written before this existed) degrades to "no source-file inputs" rather
	// than crashing -- the gate token still falls back to hashing the report itself.
	const filesRead = result.filesRead ?? [];

	// D-zero-config-scan: an empty `terms` array is how bin/bskel.mjs's cmdScan signals its new
	// zero-flag "inventory" mode (neither --terms nor --feature was given) -- every detected module
	// is listed exactly as the adapter found it, with NO term-matching/scoring/collision-detection
	// performed. Faking `score: 0` here would be actively misleading -- 0 already means "scored,
	// found nothing" in the existing contract -- so each module is built as an explicit allowlist
	// (never `{...m}`), which guarantees `score`/`evidence`/`capped_signals` are genuinely ABSENT
	// from the object, not merely `undefined`, and stops any future adapter-internal field from
	// leaking into this report shape by accident.
	const isInventory = terms.length === 0;
	let relatedModules;
	let collisions;
	let verdict;
	if (isInventory) {
		relatedModules = modules
			.map((m) => ({ module: m.module, controllers: m.controllers, entities: m.entities, enums: m.enums, dtos: m.dtos }))
			.sort((a, b) => a.module.localeCompare(b.module)); // deterministic -- no score to sort by
		collisions = []; // not "nothing collides" -- nothing was CHECKED. See the disclaimer below.
		verdict = 'inventory';
	} else {
		// O6: score alone isn't a deterministic sort key -- two modules tying on score fall back to
		// whatever order they were already in, which traces back to non-deterministic rg discovery
		// order in the adapters above (mitigated there too, but a second determinism layer here is
		// cheap and doesn't depend on every adapter getting it right). Module name is a stable,
		// meaningful secondary key.
		const scored = modules
			.map((m) => {
				const { score, evidence, cappedSignals } = scoreModule(m, terms);
				return { ...m, score, evidence, capped_signals: cappedSignals };
			})
			.sort((a, b) => b.score - a.score || a.module.localeCompare(b.module));

		relatedModules = scored.filter((m) => m.score > 0);
		collisions = relatedModules.filter((m) => m.score >= COLLISION_THRESHOLD);

		verdict = 'greenfield';
		if (collisions.length > 0) verdict = 'collision';
		else if (relatedModules.length > 0) verdict = 'adjacent';
	}

	const unknowns = [];
	// D-zero-config-scan: the FIRST unknowns entry in inventory mode -- visible in --json too, not
	// just prose a human might skim past -- so nothing downstream (human or agent) backfills a
	// relevance/collision judgment this report never made. See D-greenfield-parameters's safe/
	// unsafe line: every module/controller/entity listed below is a real, observed fact about this
	// repo; this disclaimer is what keeps "here's what exists" from being read as "here's what's
	// safe to build".
	if (isInventory) {
		unknowns.push(
			'this is an unscored inventory of every module this adapter found -- no term-matching, ' +
			'relevance scoring, or collision/greenfield classification was performed against any ' +
			'specific feature idea. Re-run with --terms <keywords> or --feature <id> to check a ' +
			'specific idea against this repo before treating anything here as "safe" or "colliding".',
		);
	}
	// D-zero-config-scan: without `rg`, every real adapter's detect() silently degrades (a blanket
	// try/catch around the rg shell-out returns [] on failure -- see scanners/text-util.mjs's
	// listRgFiles()), so a real Spring/FastAPI/Express repo can look indistinguishable from one
	// this tool genuinely doesn't recognize. `rg_available` (always present on the returned report,
	// both modes) is the machine-checkable signal; this is the human-readable one.
	if (!rgAvailable) {
		unknowns.push(
			'ripgrep (`rg`) was not found on PATH -- every real scanner adapter depends on it for file ' +
			'discovery, so a low-confidence or apparently-empty result here may simply mean `rg` is ' +
			'missing, not that this repo lacks recognizable backend structure. Install it (`brew ' +
			'install ripgrep`) and re-run, or run `bskel doctor` for full diagnostics.',
		);
	}
	if (!includeDb) {
		unknowns.push('DB not scanned (Plane C is opt-in via --db --database-url-env <NAME>) -- pass --db to scan migration files, add --database-url-env for live introspection too. See A4 in CATALOG.md.');
	} else if (!dbSchema?.live) {
		unknowns.push('DB not live-introspected (Plane C needs --database-url-env <NAME> in addition to --db) -- migration files only, no live drift check performed.');
	}
	if (dbSchema?.live) {
		unknowns.push(...computeDbDrift(dbSchema.live.tables, relatedModules));
	}
	// A1 §7: this scan can't correct a global path prefix (only --openapi-file's real-document
	// reconciliation can, see D-openapi-reconciliation) -- but it CAN tell a user who doesn't know
	// that flag exists that the defect is likely present, before they ever emit a wrong contract.
	if (pathPrefixSignals.length > 0) {
		const detail = pathPrefixSignals
			.map((s) => `${s.kind} in ${s.file}${s.prefix ? ` (prefix "${s.prefix}")` : s.pattern ? ` (pattern "${s.pattern}")` : ''}`)
			.join('; ');
		unknowns.push(
			`this repo applies a global path prefix outside controller source (${detail}) -- contract ` +
			'paths built from source annotations alone (no --openapi-file) will be missing it. Generate ' +
			'a real OpenAPI document and pass it to `bskel contract emit --openapi-file <path>`. See ' +
			'D-openapi-reconciliation in DECISIONS.md.',
		);
	}

	return {
		schema: 'sbf.scan-report/2',
		terms,
		adapter,
		confidence,
		api_surface_source: apiSurfaceSource,
		verdict,
		rg_available: rgAvailable,
		path_prefix_signals: pathPrefixSignals,
		related_modules: relatedModules,
		collisions,
		unknowns,
		files_read: filesRead,
		...(dbSchema ? { db_schema: dbSchema } : {}),
	};
}
